### ISSUE TITLE
Rust on Windows does not add lib prefix

### ISSUE THREAD

**Issue by sinankeskin** [danielpclark/faster_path#2]
When I compile the library with Rust on Windows it didn't add the "lib" prefix to library name.
I tested on Linux Mint also but Rust on Linux did.

Library names:

Windows: **faster_path.dll**
Linux:  **libfaster_path.so**

**Comment by danielpclark** [comment]
Can you open up an irb window and tell me what `RUBY_PLATFORM` returns?

**Comment by sinankeskin** [comment]
Of course. Here: **x64-mingw32**

Also I was fixed this issue with this sloppy line.

```
ffi_lib "#{File.dirname(__FILE__)}/../target/release/"  + (RUBY_PLATFORM =~ /mswin|mingw|cygwin/ ? 'faster_path.dll' : 'libfaster_path.so')
```

**Comment by danielpclark** [comment]
Where did you get the list for Windows platform aliases?

**Comment by sinankeskin** [comment]
I believe this is the link where i get.

http://stackoverflow.com/questions/4871309/what-is-the-correct-way-to-detect-if-ruby-is-running-on-windows

**Comment by danielpclark** [comment]
Alright the master branch should now support Windows https://github.com/danielpclark/faster_path/commit/2bf47f6188b1831b926e667d977d6402dfff124b .  Can you test it before I release it as a new gem version?

**Comment by sinankeskin** [comment]
No ```cygwin``` can not be a linux. It's a linux simulator on Windows.

I agree with using ``Gem.win_platform?`` but if you want to check without dependency I think you should go with ``RUBY_PLATFORM =~ /mswin|mingw|cygwin/``. I believe these 3 alias are suffice enough.

**Comment by danielpclark** [comment]
There's no dependency required at all for Gem.  It's built in.

**Comment by danielpclark** [comment]
Oh, unless they're no MRI?

**Comment by sinankeskin** [comment]
I think you should check the Ruby engine also but i don't know how FFI supports.

Here is the nokogiri's engine check line.
``if defined?(RUBY_ENGINE) && RUBY_ENGINE == "jruby"``

**Comment by danielpclark** [comment]
I'm not sure what the file name will be with jRuby.  I think I'd rather wait for a jRuby user to open an issue and have details available.

Looking into `Gem.win_platform?` I see that Jekyll https://github.com/jekyll/jekyll/issues/3721 uses it.  And one other issue raised online had something about Java detection and another person said this issue was already raised & fixed for rubygems.

I'd rather trust the implementation that's been thoroughly vetted and that way I don't have to maintain future Windows possibilities myself.  Other then that I'll wait till it becomes an issue some one needs to raise as it doesn't look like there will be a problem.

**Comment by sinankeskin** [comment]
I tested on Windows with ``Ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]`` and it works as should. Thanks again.

**Comment by danielpclark** [comment]
Alright!  New gem version coming out! :smiley:
