### ISSUE TITLE
Asserts mean UB

### ISSUE THREAD

**Issue by steveklabnik** [danielpclark/faster_path#40]
Currently, this code can cause undefined behavior, as the `assert!`s will unwind into Ruby. Luckily, we just stabilized http://doc.rust-lang.org/stable/std/panic/fn.catch_unwind.html for exactly this case :smile: 

I'd be willing to send a PR to implement this.

**Comment by danielpclark** [comment]
I'd love to see it, thanks!

**Comment by steveklabnik** [comment]
Cool. I might not get to it right away, so if someone else is quite eager, have at it. But if not, I'll get to it :+1:

**Comment by danielpclark** [comment]
Quick question.  I've had the current methods re-implemented with an `if` condition instead of the `assert!` but now they are slower for it.  Can this be used to get back the performance or do you know if it comes at a cost?

**Comment by steveklabnik** [comment]
Hm, interesting. First off, I'd be interested in how you're testing. assert! fundamentally is an if: https://github.com/rust-lang/rust/blob/master/src/libcore/macros.rs#L60-L71

**Comment by danielpclark** [comment]
The test is the end result of how long it takes for the ruby method (written in rust) to run.  The method `FasterPath.chop_basename` was 60% faster than Ruby's when it made 3 Rust method calls that had `assert!`.  After changing those to `if input.is_null() { return input }` in those 3 rust methods the `FasterPath.chop_basename` benchmark dropped down to only being 50% faster than Ruby's implementation of `Pathname#chop_basename`

**Comment by steveklabnik** [comment]
Hmmmmm

**Comment by danielpclark** [comment]
We've moved away from `assert!` so I'll close this.

_I suspect my benchmark results in my last statement here had to do with tests that were fast because it would quickly exit with nil as a result.  It was some weird behavior where the tests would still pass and the code would behave properly yet assets in Rails didn't load._

_There was a brief time in the beginning of this project where that occurred.  It was resolved but never understood why the tests would pass.  I'm guessing the test framework itself used some of the modified code at that time to verify the results._
